[release]

; Nome público da aplicação.
; Pode conter espaços, acentos e caracteres UTF-8.
name = ES32Lab nas Eleições 2026

; Pessoa, empresa ou organização responsável pela aplicação.
developer = ES Developer

; Versão publicada da aplicação.
; Recomendado utilizar versionamento no formato X.Y.Z.
version = 2.5.4

; Data correspondente à versão.
; Formato obrigatório: AAAA-MM-DD.
version_date = 2026-10-08

; Descrição pública da aplicação.
description = Acompanhe dados públicos das Eleições 2026 disponibilizados pelo TSE diretamente na ES32Lab.

; Imagem de apresentação.
; Opcional. Se ausente, a loja poderá utilizar uma imagem padrão.
thumbnail_url = https://images.tcdn.com.br/img/editor/up/1273877/abertura_oficial_6ac66675cd75d.jpg

; Vídeo relacionado à aplicação.
; Opcional.
video_url = https://www.youtube.com/watch?v=U_iIK7eju4Y&list=PLpVVewmHgD_LDEXAvsAxDWjS-3XCfZlZi

; Palavras-chave para busca e classificação.
; No platformio.ini são separadas por vírgula.
; No manifest.json o gerador poderá convertê-las para uma matriz JSON.
keywords = ES32Lab, ESP32, Eleições 2026, TSE, Wi-Fi, OTA, Arduino IDE

; Nome-base dos arquivos binários, SEM a extensão .bin.
;
; Exemplos derivados automaticamente:
; es32lab_eleicoes.bin
; es32lab_eleicoes-data.bin
; es32lab_eleicoes-full.bin
bin_name = es32lab_eleicoes

; Repositório utilizado para publicação.
; Formato esperado para GitHub: ORGANIZACAO/REPOSITORIO
repository = ESDeveloperBR/ES32Lab-Eleicoes

; Site oficial da aplicação ou desenvolvedor.
; Opcional.
website = https://www.esdeveloper.com.br/


[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_es32lab_ota.csv

build_flags =
    -D APP_VERSION=\"${release.version}\"
    -D APP_VERSION_DATE=\"${release.version_date}\"