[env:nodemcu-32s]

platform = espressif32
board = nodemcu-32s
framework = arduino

; ------------------------------------------------------------
; Monitor Serial
; ------------------------------------------------------------
monitor_speed = 115200

; ------------------------------------------------------------
; Dependencias
; ------------------------------------------------------------
;lib_ldf_mode = deep+

;lib_deps =
;    esdeveloper/ES32Lab
;    esdeveloper/TFT_eSPI_ES32Lab
;    bblanchon/ArduinoJson @ ^7.4.2

; ------------------------------------------------------------
; Sistema de arquivos
; ------------------------------------------------------------
board_build.filesystem = littlefs

; ------------------------------------------------------------
; Particionamento personalizado
; 2 particoes de firmware para futuro OTA + LittleFS
; ------------------------------------------------------------
board_build.partitions = partitions_es32lab_ota.csv